stages:
  - build
  - package
variables:
  HARBOR_REGISTRY: "harbor.arlth.cn"
  HARBOR_USERNAME: "root"
  HARBOR_PASSWORD: "Hx123456@"
  HARBOR_GROUP: "ued"
  BRANCH: $CI_COMMIT_BRANCH
  TURBO_TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJVc2VyIjoiSGl4dHJpcG8ifQ.Ac1gODcoTut8ZaNJIfosuVLoh5jXAQKKXupfja-QYog

build:
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH == "dev" || $CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "ci"
      changes:
        - package.json
  script:
    - pnpm install --no-frozen-lockfile --ignore-scripts
    - pnpm run build
b2b-official-website:
  stage: package
  variables:
    PROJECT_NAME: 'b2b-official-website'
  trigger:
    include: build/.gitlab-ci.yml
    strategy: depend
  rules:
    - if: $CI_COMMIT_BRANCH == "dev" || $CI_COMMIT_BRANCH == "master"
      changes: [package.json]
